import { PARAMETERS } from './SharedState';

export interface Preset {
  name: string;
  params: Record<number, number>;
}

export interface PresetCategory {
  category: string;
  presets: Preset[];
}

export const PRESET_CATEGORIES: PresetCategory[] = [
  {
    category: "Atmospheric Pads",
    presets: [
      {
        name: "Nebula Morph",
        params: {
          [PARAMETERS.WT_MIX]: 0.8, [PARAMETERS.WT_POS]: 0.2, [PARAMETERS.WT_LFO_AMT]: 0.5,
          [PARAMETERS.LFO_RATE]: 0.1, [PARAMETERS.UNISON_DETUNE]: 0.5,
          [PARAMETERS.ENV_ATTACK]: 3.0, [PARAMETERS.ENV_DECAY]: 2.0, [PARAMETERS.ENV_SUSTAIN]: 0.5, [PARAMETERS.ENV_RELEASE]: 4.0,
          [PARAMETERS.FILTER_CUTOFF]: 600, [PARAMETERS.FILTER_RES]: 0.2,
          [PARAMETERS.REVERB_MIX]: 0.6, [PARAMETERS.REVERB_DECAY]: 0.9,
          [PARAMETERS.MOD_L1_CUTOFF]: 0.5, [PARAMETERS.MOD_L2_WT]: 0.3
        }
      },
      {
        name: "Ethereal Void",
        params: {
          [PARAMETERS.OSC1_MIX]: 0.5, [PARAMETERS.OSC2_MIX]: 0.5, [PARAMETERS.OSC2_DETUNE]: 7.0,
          [PARAMETERS.FILTER_CUTOFF]: 400, [PARAMETERS.FILTER_RES]: 0.4,
          [PARAMETERS.ENV_ATTACK]: 2.0, [PARAMETERS.ENV_DECAY]: 2.0, [PARAMETERS.ENV_SUSTAIN]: 0.5, [PARAMETERS.ENV_RELEASE]: 5.0,
          [PARAMETERS.REVERB_MIX]: 0.7, [PARAMETERS.DELAY_MIX]: 0.3,
          [PARAMETERS.MOD_FE_PITCH]: 0.2, [PARAMETERS.MOD_L1_RATE]: 0.4
        }
      },
      {
        name: "Deep Sea Drone",
        params: {
          [PARAMETERS.LOW_SHELF_ENABLE]: 1, [PARAMETERS.LOW_SHELF_FREQ]: 120, [PARAMETERS.LOW_SHELF_GAIN]: 12,
          [PARAMETERS.SUB_OSC_MIX]: 0.9, [PARAMETERS.NOISE_MIX]: 0.2,
          [PARAMETERS.FILTER_CUTOFF]: 300, [PARAMETERS.FILTER_RES]: 0.5,
          [PARAMETERS.ENV_ATTACK]: 5.0, [PARAMETERS.ENV_DECAY]: 2.0, [PARAMETERS.ENV_SUSTAIN]: 0.5, [PARAMETERS.ENV_RELEASE]: 8.0,
          [PARAMETERS.REVERB_MIX]: 0.6, [PARAMETERS.REVERB_DAMP]: 0.8,
          [PARAMETERS.CHAOS_AMT]: 0.05, [PARAMETERS.LFO1_MORPH]: 4.0
        }
      },
      {
        name: "Shimmering Glass",
        params: {
          [PARAMETERS.WT_MIX]: 0.9, [PARAMETERS.WT_POS]: 0.6, [PARAMETERS.WT_DETUNE]: 12.0,
          [PARAMETERS.FILTER_CUTOFF]: 5000, [PARAMETERS.FILTER_RES]: 0.1,
          [PARAMETERS.ENV_ATTACK]: 0.5, [PARAMETERS.ENV_DECAY]: 0.5, [PARAMETERS.ENV_SUSTAIN]: 0.3, [PARAMETERS.ENV_RELEASE]: 3.0,
          [PARAMETERS.REVERB_MIX]: 0.8, [PARAMETERS.DELAY_MIX]: 0.4,
          [PARAMETERS.MOD_VEL_CUTOFF]: 0.6, [PARAMETERS.MOD_AE_WT]: 0.4
        }
      }
    ]
  },
  {
    category: "Leads & Basses",
    presets: [
      {
        name: "Sync Lead",
        params: {
          [PARAMETERS.OSC_SYNC_ENABLE]: 1, [PARAMETERS.OSC1_MIX]: 0.7, [PARAMETERS.OSC2_MIX]: 0.8,
          [PARAMETERS.OSC2_DETUNE]: 12.0, [PARAMETERS.FILTER_CUTOFF]: 2000,
          [PARAMETERS.FILTER_ENV_DEPTH]: 4000, [PARAMETERS.ENV_ATTACK]: 0.01,
          [PARAMETERS.ENV_DECAY]: 0.3, [PARAMETERS.ENV_SUSTAIN]: 0.4, [PARAMETERS.ENV_RELEASE]: 0.2, [PARAMETERS.TS_MIX]: 0.5,
          [PARAMETERS.MOD_L1_PITCH]: 0.3, [PARAMETERS.MOD_FE_CUTOFF]: 0.7
        }
      },
      {
        name: "FM Bass",
        params: {
          [PARAMETERS.OSC_FM_AMT]: 0.8, [PARAMETERS.OSC1_MIX]: 0.6, [PARAMETERS.OSC2_MIX]: 0.4,
          [PARAMETERS.FILTER_CUTOFF]: 500, [PARAMETERS.FILTER_RES]: 0.7,
          [PARAMETERS.ENV_ATTACK]: 0.01, [PARAMETERS.ENV_DECAY]: 0.2, [PARAMETERS.ENV_SUSTAIN]: 0.3, [PARAMETERS.ENV_RELEASE]: 0.1,
          [PARAMETERS.TS_MIX]: 0.3, [PARAMETERS.TS_DRIVE]: 0.8,
          [PARAMETERS.MOD_VEL_CUTOFF]: 0.5, [PARAMETERS.MOD_AE_PITCH]: 0.1
        }
      },
      {
        name: "Gritty Unison",
        params: {
          [PARAMETERS.OSC1_MIX]: 0.8, [PARAMETERS.UNISON_DETUNE]: 0.6, [PARAMETERS.SUB_OSC_MIX]: 0.5,
          [PARAMETERS.FILTER_CUTOFF]: 800, [PARAMETERS.FILTER_RES]: 0.5,
          [PARAMETERS.ENV_ATTACK]: 0.02, [PARAMETERS.ENV_DECAY]: 0.4, [PARAMETERS.ENV_SUSTAIN]: 0.4, [PARAMETERS.ENV_RELEASE]: 0.2,
          [PARAMETERS.TS_MIX]: 0.6, [PARAMETERS.MOD_L2_RES]: 0.4,
          [PARAMETERS.MOD_CH_CUTOFF]: 0.2
        }
      }
    ]
  },
  {
    category: "Rhythmic",
    presets: [
      {
        name: "Sequenced Pulse",
        params: {
          [PARAMETERS.SEQ_ENABLE]: 1, [PARAMETERS.SEQ_TEMPO]: 120,
          [PARAMETERS.OSC1_MIX]: 0.8, [PARAMETERS.FILTER_CUTOFF]: 1000,
          [PARAMETERS.FILTER_RES]: 0.6, [PARAMETERS.FILTER_ENV_DEPTH]: 3000,
          [PARAMETERS.ENV_ATTACK]: 0.01, [PARAMETERS.ENV_DECAY]: 0.3, [PARAMETERS.ENV_SUSTAIN]: 0.3, [PARAMETERS.ENV_RELEASE]: 0.2,
          [PARAMETERS.SEQ_STEP_0]: 0,
          [PARAMETERS.SEQ_STEP_4]: 7, [PARAMETERS.SEQ_STEP_8]: 12,
          [PARAMETERS.MOD_L1_CUTOFF]: 0.8, [PARAMETERS.MOD_VEL_PITCH]: 0.1
        }
      },
      {
        name: "Glitch Seq",
        params: {
          [PARAMETERS.SEQ_ENABLE]: 1, [PARAMETERS.SEQ_TEMPO]: 140,
          [PARAMETERS.CHAOS_AMT]: 0.4, [PARAMETERS.WT_MIX]: 0.6,
          [PARAMETERS.FILTER_CUTOFF]: 2000, [PARAMETERS.FILTER_RES]: 0.8,
          [PARAMETERS.ENV_ATTACK]: 0.01, [PARAMETERS.ENV_DECAY]: 0.2, [PARAMETERS.ENV_SUSTAIN]: 0.2, [PARAMETERS.ENV_RELEASE]: 0.1,
          [PARAMETERS.SEQ_STEP_0]: 0,
          [PARAMETERS.SEQ_STEP_2]: 5, [PARAMETERS.SEQ_STEP_4]: 10,
          [PARAMETERS.MOD_CH_RATE]: 0.5, [PARAMETERS.MOD_L2_FX]: 0.6
        }
      }
    ]
  }
];
